# Generated by Django 2.1 on 2018-08-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('pompe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pompe')),
            ],
        ),
    ]
