# Generated by Django 2.1 on 2018-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='etat',
            field=models.CharField(choices=[('HS', 'Hors function'), ('OK', 'OK'), ('KO', 'Défaut'), ('ACK', 'Défaut acquitté'), ('AL', 'Alerte'), ('ALA', 'Alerte acquitté')], default='OK', max_length=3),
        ),
    ]
