# Generated by Django 2.1 on 2018-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180804_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompe',
            name='gpio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pompe',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
    ]
