# Generated by Django 2.1 on 2018-08-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180806_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pompe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Pompe')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
    ]
